### ISSUE TITLE
Fee is optional in transaction

### ISSUE THREAD

**Issue by rllola** [ZondaX/ledger-oasis#17]
According to the go source code the fee is optional. The application should also consider fee as optional.

https://github.com/oasislabs/oasis-core/blob/bf85e38ac24ada1642c75dbea4adc675e7a11cf9/go/consensus/api/transaction/transaction.go#L34-L45

**Comment by jleni** [comment]
I think this was fixed as part of https://github.com/ZondaX/ledger-oasis-app/pull/5
@rllola could you confirm?

**Comment by rllola** [comment]
It wasn't fixed. In case of missing fee it would have return an error but from what I understand a transaction without fee is still a valid one.

However they don't seem to have tests for this ?

**Comment by jleni** [comment]
The feature was merged but it seems that there are problems with indexes.
Btw, @rllola I have added manual test for this here https://github.com/ZondaX/ledger-oasis/issues/24
You can have a look at the failing test
